#!/bin/sh

set -eo pipefail

DIR=$(dirname $0)
D=$(mktemp -du)
ROOT="$DIR/roots/$(hostname).nix"

function build {
    NIXPKGS_ALLOW_UNFREE=1 \
            nix build -f '<nixpkgs/nixos>' config.system.build \
            -I nixos-config="$ROOT" \
            -I "nixpkgs=$DIR/nixpkgs" \
            -I "nixpkgs-overlays=$DIR/overlays" \
            -I "home-manager=$DIR/home-manager" \
            --out-link "$D"
}

function switch {
    build $ROOT
    $D-18/bin/switch-to-configuration switch
}

case "$1" in
    -s* | --switch*) switch ;;
    *)               build ;;
esac

rm -rf $D*
